### PR TITLE
Update Authors and Editors

### PR DESCRIPTION
**Pull request by mprorock**
Make sure both Author and Editor sections are inline and correct

Let me know if there are additional contributors that should also be added to the "Author" section that are not currently in there.  Want to get this in line before we start issuing PRs to clarify on spec language itself

### CODE REVIEW

**Comment by OR13** [comment]
@msporny @w3c-ccg/chairs is it common to have folks listed in both authors AND editors?

Feels like we only need folks in 1 or the other, not both.

**Comment by mprorock** [comment]
> Feels like we only need folks in 1 or the other, not both.

main reason I opened this - will adjust PR as soon as we have feedback

**Comment by msporny** [comment]
> @msporny @w3c-ccg/chairs is it common to have folks listed in both authors AND editors?

Yes, it is common.

Authors are people that contributed significant and/or foundational concepts or ideas to the specification.

Editors are people that processed the public's input, PRs, etc. into a coherent, technically consistent narrative throughout the specification.

Often, people perform both roles... at present, those fields are a guess... when the specification goes to REC, those sorts of contributors are easier to identify.

**Review by msporny — APPROVED** [review]

**Review by rhiaro — APPROVED** [review]

**Review by rhiaro — CHANGES_REQUESTED** [review]
Shouldn't @dmitrizagidulin be on the authors list?

**Comment by gribneau** [comment]
I haven't added myself as an author, but I contributed a PR about a year ago to resolve #2 and would be willing to contribute further.

I am building out public identities based on this DID resolution for an upcoming project.

**Comment by mprorock** [comment]
@gribneau - let me know what email, company name, and company URL you want added ant I will get you in

**Comment by mprorock** [comment]
> Shouldn't @dmitrizagidulin be on the authors list?

This should be corrected now @rhiaro - any others That have been missed?

**Comment by gribneau** [comment]
Thanks, Mike.

> email, company name, and company URL

christian@gribneau.net
Ology Newswire, Inc.
https://ology.com

**Comment by mprorock** [comment]
@rhiaro I think everyone that needs to be added is now in.  Any further adjustments needed?

**Review by dmitrizagidulin — APPROVED** [review]
👍 
Thanks!

**Comment by mprorock** [comment]
@rhiaro - just pinging again to see if this is now good by you, and if you approve the changes?

> @rhiaro I think everyone that needs to be added is now in. Any further adjustments needed?

**Review by rhiaro — APPROVED** [review]

**Pull request merged**
