### PR TITLE
Update blockchain references

### PR DESCRIPTION
**Pull request by OR13**
Fixes the JSON-LD example that uses an ethereum address.

Deemphasize blockchain in introduction.

Adds another implementation

### CODE REVIEW

**Review by tplooker — APPROVED** [review]

**Review by mprorock — APPROVED** [review]

**Review by dmitrizagidulin — APPROVED** [review]
👍

**Review by mkhraisha — APPROVED** [review]

**Comment by OR13** [comment]
Who can merge?

**Comment by mkhraisha** [comment]
@OR13 code owners appear to be you and @mprorock, I'm assuming because you're asking, you don't have write access?

**Comment by mprorock** [comment]
merging - been open long enough with approvals

**Pull request merged**
